---
- name: Listar todos los usuarios de RACF
  hosts: zos_servers # Asegúrate de que este grupo/host exista en tu inventario de AWX
  gather_facts: false # Recomendado para z/OS

  tasks:               # <--- This line is offending, likely due to indentation
    - name: Obtener información de todos los usuarios de RACF
      ibm.ibm_zos_core.zos_user:
        name: "*"
        state: present
        return_attributes:
          - 'ALL'

      register: racf_users_info

    - name: Mostrar nombres de usuario y UIDs (o otros atributos)
      ansible.builtin.debug:
        msg: |
          Usuario: {{ item.name }}
          UID: {{ item.attributes.UID | default('N/A') }}
          Default Group: {{ item.attributes.DFLTGRP | default('N/A') }}
          Last Logon: {{ item.attributes.LASTLOGON | default('N/A') }}
          Otras Propiedades: {{ item.attributes | to_nice_json(indent=2) }}
      loop: "{{ racf_users_info.users }}"
      when: racf_users_info.users is defined and racf_users_info.users | length > 0

    - name: Informar si no se encontraron usuarios
      ansible.builtin.debug:
        msg: "No se encontraron usuarios de RACF o no se pudo obtener información."
      when: racf_users_info.users is not defined or racf_users_info.users | length == 0
