---
# Este playbook se conecta a un sistema z/OS y ejecuta el comando LISTUSER de RACF.
- name: Listar información de usuario RACF
  hosts: 10.10.130.225 # Asegúrate de que 'zos_systems' coincida con tu grupo de hosts en el inventario de AWX
  gather_facts: false # No es necesario recolectar facts del sistema z/OS para esta tarea

  vars:
        racf_user_to_list: "YOURUSER" 
  tasks:
    - name: Ejecutar comando LISTUSER en z/OS
      # Usamos el módulo zos_tso_command de la colección ibm.ibm_zos_core
      # Asegúrate de tener la colección instalada en tu entorno de ejecución de AWX.
      ibm.ibm_zos_core.zos_tso_command:
        # El comando TSO a ejecutar. LISTUSER es un comando RACF.
        command: "LISTUSER {{ racf_user_to_list }}"
        # Indicar que la salida de la consola debe ser capturada.
        # Esto es importante para ver el resultado del comando.
        
      register: racf_output # Almacena la salida del comando en una variable llamada 'racf_output'
      environment: # <--- ¡AÑADIR ESTO!
        LIBPATH: "/usr/lpp/IBM/zoautil/lib:${LIBPATH}" # <--- ¡Y ESTO!

    - name: Mostrar la salida del comando LISTUSER
      ansible.builtin.debug:
        var: racf_output.content # Muestra el contenido de la salida del comando RACF
