- hosts: 10.10.130.225
  gather_facts: no

  vars:
    python_home: "/Z31A/usr/lpp/IBM/cyp/pyz"

  environment:
    PYTHON_HOME: "{{ python_home }}"
    LIBPATH: "{{ python_home }}/lib:/Z31A/usr/lpp/IBM/zoautil/lib:{{ ansible_env.LIBPATH | default('') }}"
    PATH: "{{ python_home }}/bin:/Z31A/usr/lpp/IBM/zoautil/bin:{{ ansible_env.PATH | default('') }}"
    PYTHONPATH: "/Z31A/usr/lpp/IBM/cyp/pyz"
    ZOAU_HOME: "/Z31A/usr/lpp/IBM/zoautil"

  tasks:
    - name: Probar ZOAU con listado de datasets
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - LISTDS 'SYS1.PARMLIB'

