---
- name: Leer dataset en z/OS
  hosts: zos
  gather_facts: no
  collections:
    - ibm.ibm_zos_core

  tasks:
    - name: Leer contenido del dataset
      zos_fetch:
        src: "MY.USER.DATA"
        dest: "./descargas/"
        is_binary: false
      register: resultado

    - name: Mostrar ruta del archivo descargado
      debug:
        msg: "Archivo descargado en: {{ resultado.dest }}"
