- hosts: 10.10.130.225
  gather_facts: no

  vars:
    python_home: "/Z31A/usr/lpp/IBM/cyp/pyz"
    zoau_home: "/Z31A/usr/lpp/IBM/zoautil"

  environment:
    PYTHON_HOME: "{{ python_home }}"
    LANG: "C"
    LC_ALL: "C"

    PYTHONPATH: "{{ python_home }}/lib/python3.11/site-packages"

    LIBPATH: >
      {{ python_home }}/lib:{{ zoau_home }}/lib:/lib:/usr/lib:{{ ansible_env.LIBPATH | default('') }}

    PATH: >
      /bin:/usr/bin:{{ python_home }}/bin:{{ zoau_home }}/bin:{{ ansible_env.PATH | default('') }}

    ZOAU_HOME: "{{ zoau_home }}"

  tasks:

    - name: Verificar que zoautil_py.gdgs est치 importable
      shell: >
         {{ python_home }}/bin/python3 -c "from zoautil_py import gdgs"
      register: zoau_check
      failed_when: false
      changed_when: false

    - name: Mostrar resultado de la verificaci칩n
      debug:
        var: zoau_check.stderr_lines
    
    
    
    - name: Verificar que zoautil_py.gdgs est치 importable
      shell: >
        {{ python_home }}/bin/python3 -c "import zoautil_py; print('gdgs' in dir(zoautil_py))"
      register: zoau_check
      changed_when: false

    - name: Mostrar resultado de la verificaci칩n
      debug:
        var: zoau_check.stdout_lines

    - name: Fetching SYS1.PARMLIB to control node
      ibm.ibm_zos_core.zos_fetch:
        src: "SYS1.PARMLIB"
        flat: false
        dest: "./download_parmlib_dir"
      register: dataset_content

    - name: Show fetch results
      debug:
        var: dataset_content
